"""GST-compliant sales invoices. Finalized invoices are immutable."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    UniqueConstraint,
)
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import InvoiceStatus, PaymentMode, TaxType
from app.models.mixins import PKMixin, TimestampMixin


class Invoice(Base, PKMixin, TimestampMixin):
    """A sales tax invoice. Number is assigned per branch at finalization."""

    __tablename__ = "invoice"
    __table_args__ = (
        # Idempotent offline sync: one server invoice per client-generated uuid.
        UniqueConstraint("client_uuid", name="uq_invoice_client_uuid"),
        UniqueConstraint("branch_id", "invoice_no", name="uq_invoice_branch_no"),
        Index("ix_invoice_org_status_date", "organization_id", "status", "invoice_date"),
        Index("ix_invoice_org_date_id", "organization_id", "invoice_date", "id"),
    )

    organization_id: Mapped[int] = mapped_column(
        ForeignKey("organization.id"), nullable=False, index=True
    )
    branch_id: Mapped[int] = mapped_column(
        ForeignKey("branch.id"), nullable=False, index=True
    )
    customer_id: Mapped[int | None] = mapped_column(ForeignKey("customer.id"), index=True)
    created_by_user_id: Mapped[int | None] = mapped_column(ForeignKey("user.id"))

    # client_uuid is generated by the POS (incl. offline) for idempotent sync.
    client_uuid: Mapped[str | None] = mapped_column(String(36), index=True)
    invoice_no: Mapped[str | None] = mapped_column(String(40))
    invoice_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)

    status: Mapped[InvoiceStatus] = mapped_column(
        SAEnum(InvoiceStatus), default=InvoiceStatus.draft, nullable=False, index=True
    )
    tax_type: Mapped[TaxType] = mapped_column(SAEnum(TaxType), default=TaxType.intra)
    payment_mode: Mapped[PaymentMode] = mapped_column(
        SAEnum(PaymentMode), default=PaymentMode.cash
    )

    # Money totals (computed server-side; source of truth is line items).
    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    discount_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    tax_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    grand_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    amount_paid: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))

    finalized_at: Mapped[datetime | None] = mapped_column(DateTime)

    items: Mapped[list["InvoiceItem"]] = relationship(
        back_populates="invoice", cascade="all, delete-orphan"
    )
    branch: Mapped["Branch"] = relationship("Branch", foreign_keys=[branch_id], viewonly=True)
    customer: Mapped["Customer | None"] = relationship("Customer", foreign_keys=[customer_id], viewonly=True)


class InvoiceItem(Base, PKMixin, TimestampMixin):
    """A single billed line. Carries batch/mfg/expiry for regulatory printing."""

    __tablename__ = "invoice_item"

    invoice_id: Mapped[int] = mapped_column(
        ForeignKey("invoice.id"), nullable=False, index=True
    )
    product_id: Mapped[int] = mapped_column(ForeignKey("product.id"), nullable=False, index=True)
    batch_id: Mapped[int | None] = mapped_column(ForeignKey("batch.id"))

    # Snapshot fields (immutable record of what was printed on the invoice).
    product_name: Mapped[str] = mapped_column(String(200), nullable=False)
    hsn_code: Mapped[str | None] = mapped_column(String(12))
    batch_no: Mapped[str | None] = mapped_column(String(80), index=True)
    mfg_date: Mapped[date | None] = mapped_column(Date)
    expiry_date: Mapped[date | None] = mapped_column(Date)

    unit: Mapped[str] = mapped_column(String(20), default="unit")
    quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    discount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0"))
    gst_rate: Mapped[Decimal] = mapped_column(Numeric(5, 2), default=Decimal("0"))

    taxable_value: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    line_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))

    invoice: Mapped["Invoice"] = relationship(back_populates="items")
